In [1]:
import numpy as np

In [ ]:
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
             [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])

print(x.shape)

In [ ]:
y = np.array(12.)
print(y.dtype)

In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
(train_X, train_y), (test_X, test_y) = tf.keras.datasets.mnist.load_data(path='mnist.npz')

In [ ]:
train_X.ndim

In [ ]:
train_X.dtype

In [ ]:
digit = train_X[4]
plt.imshow(digit, cmap=plt.cm.binary)
plt.show()

In [ ]:
new = train_X[10:100]

In [ ]:
new.shape

In [ ]:
x1 = train_X[:100, :20 , :20 ]

In [ ]:
f = np.array([1,2,3,4])

In [ ]:
f.shape

In [ ]:
def naive_relu(x):
    assert len(x.shape) == 2 # assert is a condition statement and raises error in case of exception
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] = max(x[i,j], 0)
    return x

# instead of this function you can use :

z = np.maximum(z,0)

In [ ]:
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

# instead of this function you can use :

z = x + y


In [ ]:
import time 

x = np.random.random((20,100))
y = np.random.random((20,100))

t0 = time.time()
for i in range(1000):
    z = x + y
    z = np.maximum(z,0.)
print("Took: {0:.2f}s".format(time.time() - t0))

In [ ]:
# calling the naive functions

t0 = time.time()
for _ in range(1000):
    z = naive_add(x, y)
    z = naive_relu(z)
print("Took: {0:.2f} s".format(time.time() - t0))

In [ ]:
X = np.random.random((32,10))
Y = np.random.random((10,))
Y = np.expand_axis()

In [ ]:
# reshaping:

x = np.array([[0.,1.],
             [2.,3.],
             [4.,5.]])

x.shape

In [ ]:
x = x.reshape((6,1))
x

In [ ]:
import numpy as np
import pandas as pd

# Set seed for reproducibility
np.random.seed(42)

# Generate 50 random heights (between 140 cm and 200 cm)
heights = np.random.uniform(140, 200, 50)

# Generate 50 random weights (between 50 kg and 100 kg)
weights = np.random.uniform(50, 100, 50)

# Combine into a dataset


In [ ]:
def loss():
    loss = (y_pred - y_true)^2

In [ ]:
import cv2
import matplotlib.pyplot as plt

In [ ]:
img = cv2.imread('honey1.png', cv2.IMREAD_GRAYSCALE)
img = img
plt.imshow(img, cmap = 'gray')
plt.show()

In [ ]:
img.shape

In [ ]:
x = np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[11,12,13,14,15,16,17,18],[11,12,13,14,15,16,17,18],[11,12,13,14,15,16,17,18],[11,12,13,14,15,16,17,18]])

In [ ]:
x

In [ ]:
l = int(len(x))

In [ ]:
l

In [ ]:
x[0:int(l/2),0:int(l/2)]

In [ ]:
x[0:int(l/2),int(l/4):int(l-(l/4))]

In [ ]:
x[0:int(l/2),int(l/2):]

In [ ]:
x[int(l/4):int(l-(l/4)),0:int(l/2)]

In [ ]:
x[int(l/4):int(l-(l/4)),int(l/4):int(l-(l/4))]

In [ ]:
x[int(l/4):int(l-(l/4)),int(l/2):]

In [ ]:
x[int(l/2):,0:int(l/2)]

In [ ]:
x[int(l/2):,int(l/4):int(l-(l/4))]

In [ ]:
x[int(l/2):,int(l/2):]

In [ ]:
l = int(len(img))

In [ ]:
d = [
img[0:int(l/2),0:int(l/2)],
img[0:int(l/2),int(l/4):int(l-(l/4))],
img[0:int(l/2),int(l/2):],
img[int(l/4):int(l-(l/4)),0:int(l/2)],
img[int(l/4):int(l-(l/4)),int(l/4):int(l-(l/4))],
img[int(l/4):int(l-(l/4)),int(l/2):],
img[int(l/2):,0:int(l/2)],
img[int(l/2):,int(l/4):int(l-(l/4))],
img[int(l/2):,int(l/2):]
]


for i in d:
    plt.imshow(i, cmap = 'gray')
    plt.show()
    
    

CNN Implementation

In [29]:
# let us take the input matrix :

x = np.array([[[1,2,3],[4,5,6],[7,8,9]],
             [[2,4,6],[4,6,8],[9,4,1]],
             [[9,6,8],[1,5,3],[7,2,9]]])

x.shape

(3, 3, 3)

In [30]:
output_shape = (2, 3 - 2 + 1, 3 - 2 + 1)
kernels_shape = (2, 3, 2, 2)
kernels = np.random.randn(*kernels_shape)
biases = np.random.randn(*output_shape)

In [31]:
biases

array([[[ 0.70432395, -0.73076159],
        [-0.8757278 ,  0.2747339 ]],

       [[-0.13614052,  1.46562647],
        [ 0.24232756,  0.96606664]]])

In [35]:
# convolutional forward example
from scipy import signal

output = np.copy(biases)
for i in range(2):
    for j in range(3):
        output[i] += signal.correlate2d(x[j],kernels[i, j], "valid")
print("Output of convolutional forward\n\n",output)

Output of convolutional forward

 [[[ -1.51333613   6.76679355]
  [  5.1282547   -2.61193388]]

 [[-15.56008343 -21.15918857]
  [-20.04314216 -34.3883979 ]]]


In [36]:
# sigmoid activation forward

output = 1 / (1 + np.exp(-output)) # this is sigmoid formula

print(output)

[[[1.80444906e-01 9.98849944e-01]
  [9.94108025e-01 6.83743142e-02]]

 [[1.74719570e-07 6.46667692e-10]
  [1.97412186e-09 1.16227408e-15]]]


In [ ]:
# dense layer forward
weights = np.random.randn(output_size, input_size)
bias = np.random.randn(output_size, 1)
output = 